### ISSUE TITLE
Client that sends not enough data when streaming causes a crash for anyone receiving it

### ISSUE THREAD

**Issue by ghost** [lemunozm/termchat#33]
```
thread 'main' panicked at 'source length must be larger than area', /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/resize-0.5.5/src/lib.rs:349:9
stack backtrace:
   0: std::panicking::begin_panic
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: resize::Resizer<Format>::resize_internal
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/resize-0.5.5/src/lib.rs:349:9
   2: resize::Resizer<Format>::resize
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/resize-0.5.5/src/lib.rs:360:9
   3: <termchat::ui::FrameBuffer as tui::widgets::Widget>::render
             at ./src/ui.rs:230:13
   4: tui::terminal::Frame<B>::render_widget
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.14.0/src/terminal.rs:103:9
   5: termchat::ui::draw_video_panel
             at ./src/ui.rs:184:5
   6: termchat::ui::draw
             at ./src/ui.rs:31:9
   7: termchat::renderer::Renderer<W>::render::{{closure}}
             at ./src/renderer.rs:26:36
   8: tui::terminal::Terminal<B>::draw
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.14.0/src/terminal.rs:259:9
   9: termchat::renderer::Renderer<W>::render
             at ./src/renderer.rs:26:9
  10: termchat::application::Application::run
             at ./src/application.rs:118:13
  11: termchat::main
             at ./src/main.rs:53:24
  12: core::ops::function::FnOnce::call_once
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
termchat paniced, to log the error you can redirect stderror to a file, example: termchat 2> termchat_log
```

In `src/commands/send_stream/linux.rs`, I changed the `NetMessage::Stream()` to be just 

```rust
let message = NetMessage::Stream(Some((vec![], 50, 50)));
network.send_all(state.all_user_endpoints(), message);

Processing::Partial
```

As in, an empty `vec` and lying about the width/height of the video stream. This caused the panic above (on the client *receiving* this stream, not the client sending it).

Also notably is if I change the `50` to `5000000000` or some other very large number, the client hangs using 100% CPU, and you can't even Ctrl+C out of it.

Some checks that the width*height is equal to the buffer length given, and that the width and height are both reasonable, would be a good idea.

**Comment by lemunozm** [comment]
Thanks, @5225225 for the hints, I'm going to investigate it :)

**Comment by lemunozm** [comment]
https://github.com/lemunozm/termchat/pull/41 Fixed the issue.

Regarding the huge message problem that the user can not ctrl-c, I think that this is another problem that can be managed at the architectural level. Since the same can occur with any current/future huge message read.

**Comment by lemunozm** [comment]
Closed since the main reason is now resolved. Thanks!
